/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MonthChangedEventDetails, WCDatepickerLabels } from "./components/wc-datepicker/wc-datepicker";
export namespace Components {
    interface WcDatepicker {
        "clearButtonContent"?: string;
        "disableDate"?: (date: Date) => boolean;
        "elementClassName"?: string;
        "firstDayOfWeek"?: number;
        "labels"?: WCDatepickerLabels;
        "locale"?: string;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "previousMonthButtonContent"?: string;
        "previousYearButtonContent"?: string;
        "range"?: boolean;
        "showClearButton"?: boolean;
        "showMonthStepper"?: boolean;
        "showTodayButton"?: boolean;
        "showYearStepper"?: boolean;
        "startDate"?: string;
        "todayButtonContent"?: string;
        "value"?: Date | Date[];
    }
}
export interface WcDatepickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcDatepickerElement;
}
declare global {
    interface HTMLWcDatepickerElement extends Components.WcDatepicker, HTMLStencilElement {
    }
    var HTMLWcDatepickerElement: {
        prototype: HTMLWcDatepickerElement;
        new (): HTMLWcDatepickerElement;
    };
    interface HTMLElementTagNameMap {
        "wc-datepicker": HTMLWcDatepickerElement;
    }
}
declare namespace LocalJSX {
    interface WcDatepicker {
        "clearButtonContent"?: string;
        "disableDate"?: (date: Date) => boolean;
        "elementClassName"?: string;
        "firstDayOfWeek"?: number;
        "labels"?: WCDatepickerLabels;
        "locale"?: string;
        "nextMonthButtonContent"?: string;
        "nextYearButtonContent"?: string;
        "onChangeMonth"?: (event: WcDatepickerCustomEvent<MonthChangedEventDetails>) => void;
        "onSelectDate"?: (event: WcDatepickerCustomEvent<string | string[] | undefined>) => void;
        "previousMonthButtonContent"?: string;
        "previousYearButtonContent"?: string;
        "range"?: boolean;
        "showClearButton"?: boolean;
        "showMonthStepper"?: boolean;
        "showTodayButton"?: boolean;
        "showYearStepper"?: boolean;
        "startDate"?: string;
        "todayButtonContent"?: string;
        "value"?: Date | Date[];
    }
    interface IntrinsicElements {
        "wc-datepicker": WcDatepicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-datepicker": LocalJSX.WcDatepicker & JSXBase.HTMLAttributes<HTMLWcDatepickerElement>;
        }
    }
}
